### PR TITLE
Added code owners file.

### PR DESCRIPTION
**Pull request by DamianMullins**
Adding a file so that reviewers can be automatically requested for different file types on pull requests. [See this post for more details](https://github.com/blog/2392-introducing-code-owners).

So, in this template, I have taken ownership of the unit tests and will be automatically be assigned to pull requests which contain changes to any unit test files. All other file changes will assign the UI Admins.

### CODE REVIEW

**Comment by ashleynolan** [comment]
Out of interest – what does this file do? 📖  🎓 ❓

**Comment by DamianMullins** [comment]
Sorry, I should have updated the description! Will do that now.

**Comment by zlatinivanov-je** [comment]
@DamianMullins I am happy with that change to go in. Does it need merging?

**Comment by zlatinivanov-je** [comment]
@ashleynolan i was about to ask the same question but came acros this https://github.com/blog/2392-introducing-code-owners

**Comment by DamianMullins** [comment]
@zlatinivanov-je Yes please, just needs approval 😸

**Comment by DamianMullins** [comment]
@zlatinivanov-je Description has been added.

**Comment by zlatinivanov-je** [comment]
@DamianMullins oh, I meant to add something like 'reviewers can be automatically requested for different file types on pull requests. See this post for more details.' in a comment at the top of the file. Sorry for not being specific enough earlier. Just for clarity for everyone else that will touch that file later.

**Comment by DamianMullins** [comment]
@zlatinivanov-je Done.

**Pull request merged**
